method: 
  feat_type: 'eng'  # [t5, eng]
  mode: 'optuna'  # [optuna, valid, train]  # find the best hyperparameters with optuna, if false, use the set hyperparameters
  wandb: True # log the results with wandb

model:
  n_estimators: 331
  max_depth: 19
  random_state: 42
  lr: 0.015460534011613533 # learning_rate
  mcw: 2 # min_child_weight
  col: 0.5004151297321988 # colsample_bytree
  sub: 0.7179255193155967 # subsample
  gamma: 0.061634120982559146
  reg_lambda: 0.004847869163574664
  reg_alpha: 0.0016723282243910796
  weight: true
  device: 'cuda'

data:
  train_file: 'data/processed/PSPire_train.npz'
  test_file1: 'data/processed/PSPire_test_ID.npz'
  test_file2: 'data/processed/PSPire_test_noID.npz'
  seq_length_min: 0 # minimum sequence length

check:
  test_score: True # check the test score and save scores in the result file (output/results/Pred_Prob_expname.xlxs)
  save_model: False # save the model (output/models/XGmodel_expname.pkl)

expname: 'default'