method: 
  feat_type: 't5'  # t5
  topk: 64        # number of top-k T5 features to use (must match a feature_index_*.txt file)
  feat_index_file: 'shap_analysis/human_feature_index_${method.topk}.txt'
  mode: 'valid'  # [optuna, valid, train]  # find the best hyperparameters with optuna, if false, use the set hyperparameters
  wandb: True # log the results with wandb

standalone:
  model_path: 'models/LLPSense_human_top${method.topk}_shap.pkl'
  exp_task: 'predict'  # [test, predict, screen, mut, mut_screen]
  screen: ['conc', 'nacl']  # ['temp', 'conc', 'pH', 'nacl']  # for 3d case or more, ex) ['temp', 'conc'], ['temp', 'conc', 'pH']
  num_mut: 1
  mut_direction: 'negative'  # 'positive' or 'negative'

thresholds:
  nsplits: 5
  screen: 'temp'
  test_file: 'data/processed/LLPSDB_threshold.npz'

model:
  n_estimators: 374
  max_depth: 12
  random_state: 42
  lr: 0.046457425706129034
  mcw: 10
  col: 0.5000256518229218
  sub: 0.5339212082439888
  gamma: 1.0086094646433504e-05
  reg_lambda: 0.8241935744491976
  reg_alpha: 0.39527242913410765
  device: 'cuda:0'
  
data:
  train_file: 'data/processed/Dataset_LLPSense.npz'
  test_file: 'data/processed/A_IDP.npz'
  screen_file: 'data/processed/HSL_mut.npz'
  mut_file: 'data/processed/HSL.npz'
  seq_length_min: 0 # minimum sequence length
  apply_smooth: True
  smoothing_window: 15

check:
  test_score: False # check the test score and save scores in the result file (output/results/Pred_Prob_expname.xlxs)
  save_model: True # save the model (output/models/XGmodel_expname.pkl)
  irregular: False # check the irregularity of the data (screen)
  feature_importance: False

expname: 'default'

# topk=16
# model:
#   n_estimators: 698
#   max_depth: 15
#   random_state: 42
#   lr: 0.04216997801790308
#   mcw: 6
#   col: 0.500609795613046
#   sub: 0.5586574532968447
#   gamma: 0.11338357917737417
#   reg_lambda: 0.00025190152135836063
#   reg_alpha: 7.689616545293861e-05
#   device: 'cuda:0'

# topk=32
# model:
#   n_estimators: 396
#   max_depth: 15
#   random_state: 42
#   lr: 0.04611776148327386
#   mcw: 3
#   col: 0.5101988338227085
#   sub: 0.5989719386743272
#   gamma: 0.2762696059603805
#   reg_lambda: 5.408351376483233e-05
#   reg_alpha: 0.42731889327285505
#   device: 'cuda:0'

# topk=64
# model:
#   n_estimators: 374
#   max_depth: 12
#   random_state: 42
#   lr: 0.046457425706129034
#   mcw: 10
#   col: 0.5000256518229218
#   sub: 0.5339212082439888
#   gamma: 1.0086094646433504e-05
#   reg_lambda: 0.8241935744491976
#   reg_alpha: 0.39527242913410765
#   device: 'cuda:0'

# topk=128
# model:
#   n_estimators: 982
#   max_depth: 6
#   random_state: 42
#   lr: 0.08868122288056136
#   mcw: 7
#   col: 0.5115581614304935
#   sub: 0.5283892439038308
#   gamma: 6.482474201822327e-05
#   reg_lambda: 0.001634919016477315
#   reg_alpha: 0.0020763001970735087
#   device: 'cuda:0'

# topk=256
# model:
#   n_estimators: 720
#   max_depth: 6
#   random_state: 42
#   lr: 0.06431583825710183
#   mcw: 7
#   col: 0.7029697438297271
#   sub: 0.7546064067844102
#   gamma: 0.005296001969981293
#   reg_lambda: 0.17185923027497682
#   reg_alpha: 2.7113340538696122
#   device: 'cuda:0'

# topk=512
# model:
#   n_estimators: 613
#   max_depth: 17
#   random_state: 42
#   lr: 0.06405028029731967
#   mcw: 2
#   col: 0.6007507482910897
#   sub: 0.722219274813132
#   gamma: 1.8516990546209164e-05
#   reg_lambda: 0.19812136657905766
#   reg_alpha: 0.006214378045248105
#   device: 'cuda:0'